# Use a Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Update the package index and install Midnight Commander
RUN apt-get update && \
    apt-get install -y mc && \
    rm -rf /var/lib/apt/lists/*

# Run main.py when the container launches
CMD ["python", "main.py"]
