FROM eclipse-temurin:22-jre-alpine

# Install wget to download Lavalink.jar
RUN apk add --no-cache wget

# Run as non-root user
RUN addgroup -g 322 lavalink && \
    adduser -D -u 322 -G lavalink lavalink

WORKDIR /opt/Lavalink

# Download Lavalink.jar
RUN wget -O Lavalink.jar https://github.com/lavalink-devs/Lavalink/releases/download/4.0.8/Lavalink.jar

RUN chown -R lavalink:lavalink /opt/Lavalink

USER lavalink

ENTRYPOINT ["java", "-Djdk.tls.client.protocols=TLSv1.1,TLSv1.2", "-jar", "Lavalink.jar"]
